#!/bin/bash

 
for file in __init__.py __manifest__.py odoo_class.py odoo_view.xml __openerp__.py openerp_class.py openerp_view.xml wizard.py wizard_view.xml; do
   wget -O ~/.config/geany/templates/files/${file} https://raw.githubusercontent.com/vertelab/geany-odoo/master/templates/files/${file}
done

wget -O ~/.config/geany/tags/odoo.py.tags https://raw.githubusercontent.com/vertelab/geany-odoo/master/tags/odoo.py.tags
wget -O ~/.config/geany/snippets.conf https://raw.githubusercontent.com/vertelab/geany-odoo/master/snippets.conf

